CREATE TABLE NOTICE (
	NOTICE_ID VARCHAR(16) PRIMARY KEY NOT NULL,
	NOTICE_TITLE VARCHAR(32) NOT NULL,
	NOTICE_CONTENTS TEXT,
	SERVICE_YN VARCHAR(1) default 'Y' NOT NULL,
	REGISTER VARCHAR(32) NOT NULL,
	REGISTED_DATE TIMESTAMP NOT NULL,
	MODIFIER VARCHAR(32),
	MODIFIED_DATE TIMESTAMP
);