CREATE TABLE NOTICE ( 
	  NOTICE_ID VARCHAR(16) PRIMARY KEY NOT NULL
	, NOTICE_TITLE VARCHAR(32) NOT NULL
	, NOTICE_CONTENTS TEXT
	, NOTICE_YN VARCHAR(1) DEFAULT 'Y' NOT NULL
	, NOTICE_HITS INT NOT NULL DEFAULT 0
	, NOTICE_TOPFIX_YN VARCHAR(1) DEFAULT 'N' NOT NULL
	, REGISTER VARCHAR(32) NOT NULL
	, REGISTED_DATE TIMESTAMP NOT NULL
	, MODIFIER VARCHAR(32)
	, MODIFIED_DATE TIMESTAMP 
);